### ISSUE TITLE
Projetar o sistema

### ISSUE THREAD

**Issue by paulobcosta** [paulobcosta/Projeto2-ES2#5]
Projetar o sistema  em forma diagramada 
- Utilizar **Diagrama de Casos de Uso** 
- Utilizar **Diagrama de Classes** 
- Propósito:  preparar o projeto para implementação.

**Comment by paulobcosta** [comment]
Ver arquivos de "**PBR**" e "**Notas de PBR**" para ver a simplificação do sistema para geração de documentação

**Comment by felipeveigaramos** [comment]
Meu e-mail para enviar os documentos:
felipevr.utfpr@gmail.com

**Comment by felipeveigaramos** [comment]
Arquivo de casos de uso usecases.txt enviado. Sugeito a melhorias.

**Comment by felipeveigaramos** [comment]
Adicionado diagrama de classes.Favor verificar e informar se alguma melhoria é necessária.

**Comment by paulobcosta** [comment]
Issue resolvida! Adicionarei este tópico ao controle Milestones.
